[GLOBAL]
pants_version = '2.5.1rc4'
backend_packages = [
    'pants.backend.python',
    'pants.backend.python.lint.black',
    'pants.backend.python.lint.flake8',
    'pants.backend.python.typecheck.mypy',
]

[source]
root_patterns = [
    '/src/python',
    '/test/python',
]

