[GLOBAL]
pants_version = "2.5.1rc4"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = [
    "/src/python",
    "/test/python",
]

[test]
output = "all"
use_coverage = true

[pytest]
args = "-vvv"
pytest_plugins.add = [
    "pytest-mock>=3.6.1",
]
