name: CI Unit Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check linting
        run: ./pants lint src/python/gobius --black-skip

      - name: Check formatting
        run: ./pants lint src/python/gobius --flake-skip    

      - name: Check type
        run: ./pants typecheck src/python/gobius 


          
